---
- hosts: myClientsGrp
  become: true
  tasks:  
  - name: Install git using apt
    apt: 
      name: "{{ item }}" 
      state: latest
    with_items:
     - yum
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install git using yum
    yum: 
      name: "{{ item }}"
      state: latest
    with_items:
     - yum
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
